output-reports:
    active: true
    exclude:
     - 'TxtOutputReport'
     - 'XmlOutputReport'
     - 'HtmlOutputReport'
     - 'MdOutputReport'

complexity:
    LongParameterList:
        active: false
    TooManyFunctions:
        active: false

naming:
    InvalidPackageDeclaration:
        rootPackage: "io.github.mrnuggelz.opensubsonic"
    TopLevelPropertyNaming:
        constantPattern: '[A-Z][_A-Za-z0-9]*'

style:
    MagicNumber:
        active: false
