name: Dependency Submission

on:
  push:
    branches: ['master']

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run detekt
        run: ./gradlew detekt
      - uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
            sarif_file: build/reports/detekt/detekt.sarif
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
