name: Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Run detekt
        run: ./gradlew detekt
      - uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
            sarif_file: build/reports/detekt/detekt.sarif
      - name: Run all tests with Gradle Wrapper
        run: ./gradlew allTest
