name: Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: write
        security-events: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'temurin'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Run all tests with Gradle Wrapper
        run: ./gradlew allTest
      - name: Upload Build reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: build-reports-${{ github.action }}-${{ github.run_id }}
            path: build/reports/tests/allTests

